#!/bin/bash

# Simple Script for Compile & Run C programs
# Shellcheck Passed.
# Contributors: nimendra
# Last Update: 2023-03-02 20:42
# github.com/nmdra
# twitter.com/nimendra_
# Installations👇
# Dependencies: fd, fzf, gcc,
# mv ccc ./local/bin && chmod +x ccc
# --------------------------------------------

# Colors
# RED='\033[0;31m'
GREEN='\033[0;32m'
NOCOLOR='\033[0m'

# Choosing .c file with Fzf
choose="$(fd -I -d 1 -e c | fzf --cycle --reverse)" &&
cc "$choose" -o "${choose/.c/}" && # Compile C program with Gcc
echo -e "👇$choose ${GREEN}Compiled successfully.✅${NOCOLOR}\n" &&

# Run Compiled Program
if [[ $1 == -b ]]; then
    ./"${choose/.c/}"  # Run program
else
   ./"${choose/.c/}" && rm "${choose/.c/}" # Run program & Remove Compiled program
    # echo -e "${RED}Program doesn't exist 🤯${NOCOLOR}"
fi

# $choose%.* for Remove .c extesion



