# Layout and Theme
layout=default        # Options: default, compact, mini, seekbar
icon_theme=fluent     # Options: fluent, material
icon_style=outline    # Options: mixed, filled, outline

# Visual Adjustments
seekbar_height=medium # Options: small, medium, large, xlarge
nibbles_style=gap     # Options: gap, triangle, bar, single-bar

# Colors (Hex format)
seekbarfg_color=#E39C42

# Functional Options
speed_button=yes
title=${media-title}
language=en
